"""Starter deck: (word, part of speech, real definition). Add more rows any time."""

WORDS = [
    ("snollygoster", "n.", "a shrewd, unprincipled person, especially a politician"),
    ("borborygmus", "n.", "a rumbling or gurgling noise made by gas moving through the intestines"),
    ("absquatulate", "v.", "to leave abruptly or secretly; to abscond"),
    ("widdershins", "adv.", "in a direction contrary to the sun's course; counterclockwise"),
    ("kakistocracy", "n.", "government by the least qualified or most unprincipled citizens"),
    ("collywobbles", "n.", "stomach pain or queasiness, especially from nervousness"),
    ("gongoozler", "n.", "a person who enjoys idly watching boats and activity on canals"),
    ("ultracrepidarian", "n.", "a person who gives opinions on matters beyond their knowledge"),
    ("pandiculation", "n.", "the act of stretching and yawning, especially on waking"),
    ("crapulent", "adj.", "sick from excessive eating or drinking"),
    ("bumbershoot", "n.", "an umbrella"),
    ("cattywampus", "adj.", "askew or out of alignment; not lined up properly"),
    ("quockerwodger", "n.", "a wooden puppet worked by strings; by extension, a politician controlled by others"),
    ("groak", "v.", "to silently watch others eat, hoping to be invited to join"),
    ("mumpsimus", "n.", "a person who obstinately clings to an error or outdated custom"),
    ("nudiustertian", "adj.", "of or relating to the day before yesterday"),
    ("lethologica", "n.", "the inability to recall a particular word when needed"),
    ("zenzizenzizenzic", "n.", "the eighth power of a number"),
    ("bibliopole", "n.", "a dealer in books, especially rare or secondhand ones"),
    ("cachinnate", "v.", "to laugh loudly or immoderately"),
    ("erinaceous", "adj.", "of, like, or relating to hedgehogs"),
    ("fard", "v.", "to paint the face with cosmetics"),
    ("grimalkin", "n.", "an old female cat"),
    ("hircine", "adj.", "goatlike, especially in smell"),
    ("jentacular", "adj.", "of or relating to breakfast"),
    ("lucubration", "n.", "laborious study or writing, especially done late at night"),
    ("noctivagant", "adj.", "wandering about at night"),
    ("oxter", "n.", "the armpit"),
    ("pettifogger", "n.", "an inferior lawyer who handles petty cases using dubious practices"),
    ("quidnunc", "n.", "a person eager to know the latest news and gossip"),
    ("sialoquent", "adj.", "spraying saliva while speaking"),
    ("tatterdemalion", "n.", "a person dressed in ragged, tattered clothing"),
    ("uhtceare", "n.", "anxiety felt while lying awake in the hours before dawn"),
    ("wabbit", "adj.", "exhausted or slightly unwell (Scots)"),
    ("zarf", "n.", "an ornamental holder, usually of metal, for a handleless coffee cup"),
    ("aglet", "n.", "the small plastic or metal sheath at the end of a shoelace"),
    ("philtrum", "n.", "the vertical groove between the base of the nose and the upper lip"),
    ("vagitus", "n.", "the cry of a newborn baby"),
    ("apricity", "n.", "the warmth of the sun in winter"),
    ("brontide", "n.", "a low rumbling sound like distant thunder, heard in some regions and of uncertain origin"),
    ("deipnosophist", "n.", "a person skilled in the art of dinner-table conversation"),
    ("eructation", "n.", "the act of belching"),
    ("formication", "n.", "a sensation like insects crawling on or under the skin"),
    ("gardyloo", "interj.", "a warning cry once used in Edinburgh before throwing slops from an upper window"),
    ("hebetude", "n.", "mental dullness or lethargy"),
    ("infandous", "adj.", "too odious to be expressed or mentioned"),
    ("kenspeckle", "adj.", "conspicuous; easily recognized (Scots)"),
    ("mallemaroking", "n.", "the carousing of seamen aboard ice-bound whaling ships"),
    ("nidification", "n.", "the process of building a nest"),
    ("octothorpe", "n.", "the symbol #"),
    ("pogonotrophy", "n.", "the growing of a beard"),
    ("quomodocunquize", "v.", "to make money by any means possible"),
    ("rhadamanthine", "adj.", "rigorously strict or uncompromisingly just"),
    ("snickersnee", "n.", "a large knife; also, a fight with knives"),
    ("tergiversate", "v.", "to change one's opinions repeatedly; to equivocate"),
    ("ugsome", "adj.", "loathsome or horrible"),
    ("vomitory", "n.", "an entrance passage that opens onto the tiers of a stadium or theater"),
    ("wamble", "v.", "of the stomach, to rumble or feel queasy"),
    ("ylem", "n.", "the primordial matter from which the chemical elements are said to have formed"),
    ("zugzwang", "n.", "in chess, a position in which any move a player makes will worsen it"),
    ("crwth", "n.", "an ancient Celtic stringed instrument played with a bow"),
    ("fipple", "n.", "the plug in the mouthpiece of a recorder or tin whistle that directs the air"),
    ("lunula", "n.", "the pale crescent at the base of a fingernail"),
    ("tmesis", "n.", "the insertion of a word into the middle of another word, as in abso-blooming-lutely"),
    ("nubivagant", "adj.", "wandering in or among the clouds"),
    ("ombrifuge", "n.", "a shelter from rain"),
    ("psithurism", "n.", "the rustling sound of wind in the trees"),
    ("susurrus", "n.", "a soft whispering or murmuring sound"),
    ("obambulate", "v.", "to walk about; to wander aimlessly"),
    ("famulus", "n.", "an attendant or assistant, especially to a scholar or magician"),
    ("hobbledehoy", "n.", "a clumsy or awkward youth"),
    ("lickspittle", "n.", "a person who behaves obsequiously to those in power"),
    ("hornswoggle", "v.", "to cheat or swindle"),
    ("sesquipedalian", "adj.", "given to using long words"),
    ("impignorate", "v.", "to pledge or pawn"),
    ("callithumpian", "adj.", "of or relating to a noisy, discordant parade or serenade"),
    ("yonderly", "adj.", "mentally distant; absent-minded"),
    ("dysania", "n.", "great difficulty getting out of bed in the morning"),
    ("cacoethes", "n.", "an irresistible urge to do something inadvisable"),
    ("fanfaronade", "n.", "swaggering or boastful talk"),
    ("jobbernowl", "n.", "a stupid person; a blockhead"),
    ("ninnyhammer", "n.", "a foolish or stupid person"),
    ("sternutation", "n.", "the act of sneezing"),
]
